name: Publish Website
on:
  push:
    branches:
      - main


jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: practice-site.petyaferreira.com
        remote-user: u215844095
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/u215844095/practice-site.petyaferreira.com/wp-content/themes/deploy-theme/